[2024-09-19T01:22:12.613+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T01:22:12.632+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T01:20:43.485583+00:00 [queued]>
[2024-09-19T01:22:12.642+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T01:20:43.485583+00:00 [queued]>
[2024-09-19T01:22:12.642+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-19T01:22:12.657+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_data_processing> on 2024-09-19 01:20:43.485583+00:00
[2024-09-19T01:22:12.665+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_processing', 'manual__2024-09-19T01:20:43.485583+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmpic3ddiw0']
[2024-09-19T01:22:12.667+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_data_processing
[2024-09-19T01:22:12.669+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=219) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-19T01:22:12.671+0000] {standard_task_runner.py:72} INFO - Started process 220 to run task
[2024-09-19T01:22:12.718+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T01:20:43.485583+00:00 [running]> on host 87bbd8b92491
[2024-09-19T01:22:12.825+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T01:20:43.485583+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T01:20:43.485583+00:00'
[2024-09-19T01:22:12.827+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T01:22:12.858+0000] {docker.py:367} INFO - Starting docker container from image us-west1-docker.pkg.dev/nba-fantasy-ml/nba-data-pipeline-repo/data-processing:latest
[2024-09-19T01:22:12.867+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-19T01:22:13.730+0000] {docker.py:438} INFO - 2024-09-19 01:22:13,728 - INFO - Starting data processing...
[2024-09-19T01:22:13.732+0000] {docker.py:438} INFO - 2024-09-19 01:22:13,728 - ERROR - Error while connecting to PostgreSQL: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
[2024-09-19T01:22:13.738+0000] {docker.py:438} INFO - 	Is the server running locally and accepting connections on that socket?
[2024-09-19T01:22:13.739+0000] {docker.py:438} INFO - Database connection failed.
[2024-09-19T01:22:13.741+0000] {docker.py:438} INFO - 2024-09-19 01:22:13,728 - INFO - Successfully processed player_box_scores/2023-24/nba_player_stats_2023-24_2023-10-24_to_2023-10-25_2024-09-19_01-22-11.csv
[2024-09-19T01:22:13.951+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T01:22:13.952+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_processing, run_id=manual__2024-09-19T01:20:43.485583+00:00, execution_date=20240919T012043, start_date=20240919T012212, end_date=20240919T012213
[2024-09-19T01:22:13.970+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T01:22:13.987+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-19T01:22:13.988+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
