[2024-09-19T00:44:37.479+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T00:44:37.510+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-19T00:44:36.928174+00:00 [queued]>
[2024-09-19T00:44:37.521+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-19T00:44:36.928174+00:00 [queued]>
[2024-09-19T00:44:37.521+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-19T00:44:37.539+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_data_ingestion> on 2024-09-19 00:44:36.928174+00:00
[2024-09-19T00:44:37.549+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_ingestion', 'manual__2024-09-19T00:44:36.928174+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmpworwdutv']
[2024-09-19T00:44:37.552+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask run_data_ingestion
[2024-09-19T00:44:37.555+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=247) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-19T00:44:37.556+0000] {standard_task_runner.py:72} INFO - Started process 248 to run task
[2024-09-19T00:44:37.610+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-19T00:44:36.928174+00:00 [running]> on host 60f4d263d5b1
[2024-09-19T00:44:37.806+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T00:44:36.928174+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T00:44:36.928174+00:00'
[2024-09-19T00:44:37.807+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T00:44:37.838+0000] {docker.py:367} INFO - Starting docker container from image us-west1-docker.pkg.dev/nba-fantasy-ml/nba-data-pipeline-repo/data-ingestion:latest
[2024-09-19T00:44:37.847+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-19T00:45:12.934+0000] {docker.py:438} INFO - Processing batch 1/1
[2024-09-19T00:45:12.935+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406060BOS.html for game date 2024-06-06
[2024-09-19T00:45:12.935+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406090BOS.html for game date 2024-06-09
[2024-09-19T00:45:12.936+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406120DAL.html for game date 2024-06-12
[2024-09-19T00:45:12.936+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406140DAL.html for game date 2024-06-14
[2024-09-19T00:45:12.937+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406170BOS.html for game date 2024-06-17
[2024-09-19T00:45:12.937+0000] {docker.py:438} INFO - 2024-09-19 00:45:12,932 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe8f2793eb0>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:45:13.339+0000] {docker.py:438} INFO - 2024-09-19 00:45:13,338 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe8f2793dc0>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:45:14.146+0000] {docker.py:438} INFO - 2024-09-19 00:45:14,143 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe8f27bc070>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:45:15.754+0000] {docker.py:438} INFO - 2024-09-19 00:45:15,752 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe8f27bc190>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:45:18.965+0000] {docker.py:438} INFO - 2024-09-19 00:45:18,963 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe8f27bc430>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:45:18.970+0000] {docker.py:438} INFO - Failed to upload player_box_scores/2023-24/nba_player_stats_2023-24_2024-06-01_to_2024-06-30_2024-09-19_00-45-12.csv: HTTPConnectionPool(host='minio', port=9000): Max retries exceeded with url: /nba-raw-data?location= (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe8f27bc5e0>: Failed to resolve 'minio' ([Errno -2] Name or service not known)"))
[2024-09-19T00:45:18.971+0000] {docker.py:438} INFO - 2024-09-19 00:45:18,969 - INFO - Data successfully uploaded to MinIO bucket 'nba-raw-data' as 'player_box_scores/2023-24/nba_player_stats_2023-24_2024-06-01_to_2024-06-30_2024-09-19_00-45-12.csv'
[2024-09-19T00:45:18.971+0000] {docker.py:438} INFO - 2024-09-19 00:45:18,969 - INFO - Data ingestion completed successfully
[2024-09-19T00:45:19.249+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T00:45:19.250+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_ingestion, run_id=manual__2024-09-19T00:44:36.928174+00:00, execution_date=20240919T004436, start_date=20240919T004437, end_date=20240919T004519
[2024-09-19T00:45:19.291+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T00:45:19.313+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-19T00:45:19.315+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
