[2024-09-18T21:59:55.569+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T21:59:55.586+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-18T21:59:54.095667+00:00 [queued]>
[2024-09-18T21:59:55.594+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-18T21:59:54.095667+00:00 [queued]>
[2024-09-18T21:59:55.596+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-18T21:59:55.608+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): run_data_ingestion> on 2024-09-18 21:59:54.095667+00:00
[2024-09-18T21:59:55.617+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_ingestion', 'manual__2024-09-18T21:59:54.095667+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmpuj4bu62s']
[2024-09-18T21:59:55.621+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=221) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-18T21:59:55.622+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_data_ingestion
[2024-09-18T21:59:55.622+0000] {standard_task_runner.py:72} INFO - Started process 225 to run task
[2024-09-18T21:59:55.673+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-18T21:59:54.095667+00:00 [running]> on host e4c1837770e9
[2024-09-18T21:59:55.768+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T21:59:54.095667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-18T21:59:54.095667+00:00'
[2024-09-18T21:59:55.769+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T21:59:55.772+0000] {main.py:73} ERROR - Error in data ingestion: [Errno 2] No such file or directory: '/app/data_pipeline_services/config/scraping_config.yml'
[2024-09-18T21:59:55.772+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-18T21:59:55.782+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T21:59:55.783+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_ingestion, run_id=manual__2024-09-18T21:59:54.095667+00:00, execution_date=20240918T215954, start_date=20240918T215955, end_date=20240918T215955
[2024-09-18T21:59:55.806+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-18T21:59:55.829+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-18T21:59:55.831+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
